### ISSUE TITLE
Allow ASTFactory to throw IOException

### ISSUE THREAD

**Issue by hinerm** [bobbylight/RSTALanguageSupport#26]
Hello. We're trying to add RSTALanguageSupport to scripting in [ImageJ](http://imagej.net/Welcome) and are running into the problem that if there is a syntax error in Java, you get the cool error highlighting but also print a stacktrace.

This is because [ASTFactory](https://github.com/bobbylight/RSTALanguageSupport/blob/2.5.7/src/main/java/org/fife/rsta/ac/java/rjc/parser/ASTFactory.java#L601) is catching the `IOException` and printing it before it gets to the [JavaParser](https://github.com/bobbylight/RSTALanguageSupport/blob/2.5.7/src/main/java/org/fife/rsta/ac/java/JavaParser.java#L145-L148) which, as desired, doesn't print the stack trace.

So it seems like maybe `ASTFactory` shouldn't be handling the exceptions, but allow the parsers to do so instead..? Or maybe it's sufficient to just not print the stack trace at the `ASTFactory` level.

**Comment by bobbylight** [comment]
Yes, that is a little sloppy.  I'll clean it up!

**Comment by bobbylight** [comment]
I've removed the `printStackTrace()` call.  In the future I'll refactor things so the Java parsing throws CompilationExceptions for unrecoverable compile exceptions, vs. IOExceptions for actual I/O errors, and add some sort of debugging or logging for the former.
