### ISSUE TITLE
Usage examples for org.fife.rsta.ac.java.SourceCompletionProvider or JavaCompletionProvider. 

### ISSUE THREAD

**Issue by christianleger** [bobbylight/RSTALanguageSupport#30]
Hello, 

I'm very interested in putting your library to use in my project. However, I've had no luck getting anything other than basic completions to work. Do you have example usages available to demonstrate, for instance, completion of import statements (I imagine everything in the basic Java API would be completable)?

When I'm interested in Java completion, should I primarily be working with org.fife.rsta.ac.java.JavaCompletionProvider, or with org.fife.rsta.ac.java.SourceCompletionProvider? 

Many thanks in advance.

**Comment by ruggy** [comment]
I've now succeeded, after a lot of trial and error and debugging, in identifying that I can use a LanguageSupportFactory to create a LanguageSupport for Java, and now I'm able to get syntax highlighting and local variable lookups. However, I haven't yet found a mechanism to add the Java API to the set of completion lookups - for example, if I were to type java.util. and then hit <tab> I would like to see options come up, but this doesn't happen out-of-the-box. Is there a way to add rt.jar to the LanguageSupportFactory?

**Comment by bobbylight** [comment]
You need to add jars, and optionally, their sources, to the `JarManager` associated with your `JavaLanguageSupport`.  Check out [the JarManager API](https://github.com/bobbylight/RSTALanguageSupport/blob/master/src/main/java/org/fife/rsta/ac/java/JarManager.java).

Also, in the RSTALanguageSupport source, check out the `org.fife.rsta.ac.demo` source.  Particularly, the `DemoRootPane` class has an example of adding code completion for the currently-running JVM's `rt.jar`:

```java
LanguageSupportFactory lsf = LanguageSupportFactory.get();
LanguageSupport support = lsf.getSupportFor(SYNTAX_STYLE_JAVA);
JavaLanguageSupport jls = (JavaLanguageSupport)support;
// TODO: This API will change!  It will be easier to do per-editor
// changes to the build path.
try {
	jls.getJarManager().addCurrentJreClassFileSource();
} catch (IOException ioe) {
	ioe.printStackTrace();
}
```
