### ISSUE TITLE
Java: Annotated method parameters incorrectly identified as errors

### ISSUE THREAD

**Issue by bobbylight** [bobbylight/RSTALanguageSupport#31]
JavaLanguageSupport incorrectly flags annotations on method parameters as errors.  For example:

```java
public ResponseEntity<Foo> doSomething(@RequestBody Foo foo, HttpServletRequest request) {
```

Results in an error:

```
Expected IDENTIFIER, found "@"
```

**Comment by kovadam69** [comment]
Hi!
I already wrote to the forum regarding this issue about a year ago, also provided the code fix for it.
http://fifesoft.com/forum/viewtopic.php?f=11&t=924

**Comment by bobbylight** [comment]
The fix was implemented exactly as described in the forum poast, thanks @kovadam69!
