### ISSUE TITLE
Is there any method to make edited code pretty (format)? 

### ISSUE THREAD

**Issue by ak40u** [bobbylight/RSTALanguageSupport#52]
Hello. Is there any method to make edited code pretty (format)?

**Comment by bobbylight** [comment]
No, not baked in.  In [other projects](https://github.com/bobbylight/RText) I've used jtidy for HTML and XML and [jsonbeans](https://github.com/EsotericSoftware/jsonbeans) for JSON (I'm sure you could use jackson as well but jsonbeans is much more lightweight).
