### ISSUE TITLE
Code hint?

### ISSUE THREAD

**Issue by BeichenDream** [bobbylight/RSTALanguageSupport#54]
![1](https://user-images.githubusercontent.com/43266206/118319722-bdf46b80-b52d-11eb-87b1-2d42961e4404.jpg)
![2](https://user-images.githubusercontent.com/43266206/118319731-bf259880-b52d-11eb-9e8d-8be53bff04cf.jpg)

How to achieve the code prompt effect in Figure 1
I found that php does not provide code prompts when using Demo

**Comment by BeichenDream** [comment]
Thank you for writing such a great library

I have solved this problem. There is a code problem and I have fixed it

![3](https://user-images.githubusercontent.com/43266206/118323962-f4cd8000-b533-11eb-9e45-4d4c0fd341f4.jpg)

**Comment by bobbylight** [comment]
This has been fixed.  Note that you can also type Ctrl+Space to force the completion windows to appear.
