### ISSUE TITLE
apply my own javascript library to LanguageSupport.

### ISSUE THREAD

**Issue by inners** [bobbylight/RSTALanguageSupport#9]
Hi.

I'm trying to make my own html&javascript editor using RSTA&LS&AC.

When I make a new document using above editor, every document will use

my own made js file(kind of common library for me)  that contains public or global functions and variables.

so I want to do code-completion about above common library.

after spent whole week, I have no more idea about this.

Does anyone can help about this?

How can I apply my own js library to RSTA and do code-completion successfully?

**Comment by bobbylight** [comment]
Closing both as answered and due to age.
